version: "3.9"
services:
  servicea:
    build: 
      context: serviceA
    ports:
      - "8080:8080"
    environment:
      - SERVICEA_SERVICEB_URL=serviceb:8081
  serviceb:
    build: 
      context: serviceB
    ports:
      - "8081:8081"
